export const UPLOAD_NFT_METADATA = "UPLOAD_NFT_METADATA";
export const UPLOAD_NFT_IMAGE = "UPLOAD_NFT_IMAGE";
export const GET_LISTED_NFT_INFO = "GET_LISTED_NFT_INFO";
export const GET_NFT_INFO = "GET_NFT_INFO";
